steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gdg-node-demo:$TAG_NAME', '.']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment', 'gdg-node-demo', 'gdg-node-demo=gcr.io/$PROJECT_ID/gdg-node-demo:$TAG_NAME']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
images: ['gcr.io/$PROJECT_ID/gdg-node-demo:$TAG_NAME']