apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name:  'hpa-node'
spec: 
  scaleTargetRef: 
    apiVersion: 'extensions/v1beta1'
    kind: 'Deployment'
    name: gdg-node-demo
  minReplicas: 1
  maxReplicas: 10
  metrics:  
    - type: 'Resource'
      resource: 
        name: 'memory'
        targetAverageValue: 70Mi