apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: gdg-node-demo
  name: gdg-node-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      run: gdg-node-demo
  template:
    metadata:
      labels:
        run: gdg-node-demo
    spec:
      containers:
      - image: gcr.io/platformer-november/gdg-node-demo:v5
        name: gdg-node-demo
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 0.5m
            memory: 250Mi
          limits:
            cpu: 0.5m
            memory: 250Mi
