apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: gdg-node-demo
  name: gdg-node-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      run: gdg-node-demo
  template:
    metadata:
      labels:
        run: gdg-node-demo
    spec:
      containers:
      - image: gcr.io/platformer-november/gdg-node-demo:v1
        name: gdg-node-demo
        env:
        - name: 'type'
          value: 'workshop by k8s SL'
        resources:
          requests:
            cpu: 0.5m
            memory: 250Mi
          limits:
            cpu: 0.5m
            memory: 250Mi
